# docker-compose.kafka.yml  – single‑node KRaft cluster
services:
  kafka:
    image: apache/kafka:4.0.0          # official image
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092                      # plaintext client port
      - 9093:9093                      # controller:admin (internal)
#    environment:
      # === KRaft configuration ===============================
#      CLUSTER_ID: "demo-cluster-$(uuidgen | tr -d '-')"
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: "broker,controller"
#      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      # === Mandatory broker basics ===========================
#      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
#      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#      KAFKA_NUM_PARTITIONS: 1
#      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # === Convenience tweaks for local dev ==================
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  kafka_data:
